### ISSUE TITLE
Familiarisation with git and GitHub.

### ISSUE THREAD

**Issue by cadmiumcat** [GSS-Cogs/pmd-jenkins-library#21]
##### Tasks
- [x] Install git and [configure it](https://git-scm.com/book/en/v2/Getting-Started-First-Time-Git-Setup) to have the correct email address
- [x] Clone the [pmd-jenkins-library](https://github.com/GSS-Cogs/pmd-jenkins-library) repository. Create a branch to work from.
- [x] Add a README.md, commit and push your changes
- [x] Create a pull request on GitHub and assign someone to review it. 
- [x] Review someone else's pull request. You can [start with this one](https://github.com/GSS-Cogs/gss-utils/pull/81).
- [x] Familiarise yourself with the [Software Engineer community standards](https://github.com/ONSdigital/software-engineer-community/tree/master/workflow)

##### Key things to learn and resources: 
- git branching. [Learn by doing](https://try.github.io/)
- working with remotes, push, pull
- [pull requests](https://docs.github.com/en/free-pro-team@latest/github/collaborating-with-issues-and-pull-requests/proposing-changes-to-your-work-with-pull-requests)

There are plently of resources online. Do use others if you don't find these helpful.

**Comment by cadmiumcat** [comment]
@CharlesRendle completed all this an is now a git genius 🤓
